spring.application.name=backend
server.port=8080

# Base de donnees PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/springboot_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Initialisation des donnees (data.sql)
spring.sql.init.mode=always

# JWT
jwt.secret=MonSecretJWTTresLongPourEtreSecurise1234567890
jwt.expiration=86400000

# Upload fichiers (images produits)
spring.web.resources.static-locations=classpath:/static/
